name: javascript custom action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # trzeba pobrać kod ze względu na zamieszczenie akcji w nim
      # do akcji na zewnętrznych repozytoriach nie jest to wymagane
      - name: Get code
        uses: actions/checkout@v3
      - name: Build website
        run: npm run build
      - name: Run custom javascript action deploying site
        id: deploy
        uses: ./.github/actions/javascript-action
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          with:
            bucket: aws-s3-hosting-name
            dist-folder: ./dist
      - name: Output information
        run: |
          echo "Live url: $$ {{ steps.deploy.outputs.website-url}}"
  information:
    runs-on: ubuntu-latest
    steps:
      # trzeba pobrać kod ze względu na zamieszczenie akcji w nim
      # do akcji na zewnętrznych repozytoriach nie jest to wymagane
      - name: Get code
        uses: actions/checkout@v3
      - name: Run custom javascript action
        uses: ./.github/actions/javascript-action
