name: javascript custom action

on: workflow_dispatch

jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom javascript action
        uses: ./.github/actions/javascript-action
