name: composite custom actions

on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Load and cache dependencies
        # ścieżka relatywna do roota projektu
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
