name: Deploy React Project

on:
  # odpala się podczas pushowania nowego commita lub taga
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # pobranie kodu z repozytorium
      - name: get code
        # używa akcji, np. z marketplace
        uses: actions/checkout@v3

      # opcjonalna instalacja nowszej wersji noda
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # instalacja paczek
      - name: install packages
        # instalacja paczek z package-lock.json
        run: npm ci
      # budowanie projektu
      - name: build project
        run: npm run build
      # Deploy project
      - name: deploy project
        run: echo "deploying..."
