name: Environments

on: workflow_dispatch

# przekazanie zmiennych środowiskowych
# dostępne dla każdego job
env:
  MONGODB_DB_NAME: db-name

jobs:
  test:
    # przekazanie zmiennych środowiskowych
    # dostępne dla job "test"
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.15pwqcc.mongodb.net
      MONGODB_USERNAME: maximilian
      # przypisanie zmiennej zdefiniowanej jako secret w repozytorium
      # zmienna będzie listowana jako "***"
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        # odczytanie zmiennej, składnia dostępna dla linuxa. Dla windowsa jest inna
        run: echo "http://127.0.0.1:$PORT"
      - name: Output information
        # dwie możliwości dostępu do zmiennych
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_PASSWORD: ${{ env.MONGODB_PASSWORD }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        # "MONGODB_USERNAME" nie będzie dostępna dla tego job
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_USERNAME: $MONGODB_DB_NAME"
