name: multiple triggers - activity types

# wiele triggerów
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job"
