name: output information

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github context
        # dostęp do metadanych oferowanych przez githuba z użyciem github expression
        run: echo "${{ toJSON(github) }}"
