name: using reusable workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install packages
        run: npm ci
      - name: build project
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    # ścieżka do pliku workflow relatywna do roota projektu
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      # przekazanie wartości argumentu zdefiniowanego w "reusable-workflow.yml"
      artifact-name: dist-files
  report:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print deploy output
        run: echo "${{ needs.deploy.outputs.result }}"
