name: using reusable workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: installing packages
        run: echo "installing packages"
  deploy:
    needs: build
    # ścieżka do pliku workflow relatywna do roota projektu
    uses: ./github/workflows/reusable-workflow.yml
